export const baseURL = "http://localhost:8000/dashboard";

export const endpoints = {
    login: "auth/login",
    admin: "admin",
    user: "user",
    promotion: "promotion",
    memberDiscount: "member-discount",
    category: "category",
    generalStatus: "general",
    paymentType: "payment_type",
    item: "item",
    image: `${baseURL}/media`,
    status: "status",
    point: "point",
    delivery: "delivery-address",
    order: "order",
    faq: "faq",
    region: "region",
    shop: "shop",
    count: "count",
    role: 'role',
    permission: 'permission',
    exportItem : 'export-item',
    importItem : 'import-item',
    importCategory : 'import-category',
    exportCategory : 'export-category',
    exportOrder : 'export-order',
    exportShop : 'export-shop',
    exportUser : 'export-user'
}